### ISSUE TITLE
Add reason for using this over the csv crate

### ISSUE THREAD

**Issue by ssokolow** [jbethune/tabfile#1]
I just noticed your crate on crates.io and couldn't understand why it exists when the `csv` crate has `ReaderBuilder::delimiter`. (Especially given that `csv` is written by Andrew "BurntSushi" Gallant, who has built quite a reputation for putting out high-quality crates.)

Probably a good idea to include a section in your README explaining when one would want to choose this over `csv` or vice-versa.

**Comment by jbethune** [comment]
I wasn't aware of that crate. Thanks for pointing it out! I'll check it out and see what the differences are.
